---
- hosts: all
  become: true

  vars:
    redmine_git_url: https://github.com/redmine/redmine.git
    redmine_git_version: '4.1.1'
    ruby_install_from_source: true
    ruby_download_url: https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.gz
    ruby_version: 2.6.6
    # The state, either disabled, permissive or enforcing.
    selinux_state: permissive

  roles:
    - role: robertdebock.selinux
      tags: selinux
    - role: robertdebock.locale
      tags: locale
    - role: timezone
      tags: timezone
    - role: httpd
      tags: httpd
    - role: mamono210.ruby
      tags: ruby
    - role: postgresql
      tags: postgresql
    - role: redmine/create-pg-account-and-database
      tags: database
    - role: geerlingguy.repo-epel
      tags: repo-epel
    - role: redmine/install
      tags: redmine
    - role: redmine/add-themes
      tags: themes
    - role: passenger
      tags: passenger
