- hosts: all
  become: true

  vars:
    ruby_install_from_source: true
    ruby_download_url: https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.3.tar.gz
    ruby_version: 2.5.3
    # The state, either disabled, permissive or enforcing.
    selinux_state: permissive

  vars_files:
    - vars/default.yml

  roles:
    - role: robertdebock.selinux
    - role: timezone
    - role: httpd
    - role: geerlingguy.ruby
    - role: postgresql
    - role: redmine/create-pg-account-and-database
    - role: redmine/install
    - role: redmine/add-themes
    - role: passenger
