---
jobs:
  build:
    docker:
      - image: tomonorimatsumura/ansible-boto3:python3.8-latest

    steps:
      - checkout
      - run:
          name: Create galaxy dependencies file in 'molecule/default/'
          command: |
            cp roles/requirements.yml molecule/default/requirements.yml

      - run:
          name: Test with molecule
          command: |
            molecule test
          environment:
            EC2_REGION: ap-northeast-1
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'

version: 2
test-checkout:
  jobs:
    - build
