# Redmine intall vars

# ----------------------------------------------------------------------
# データベース情報 (変更推奨)
#----------------------------------------------------
db_host: localhost
db_name: redmine
db_password: password
db_port: 5432
db_user: redmine
# ----------------------------------------------------------------------

#----------------------------------------------------
# Redmineのチェックアウト元URL
#----------------------------------------------------
redmine_svn_url: http://svn.redmine.org/redmine/branches/4.0-stable

#----------------------------------------------------
# Redmineのデプロイ先ディレクトリ
#----------------------------------------------------
redmine_dir: /var/lib/redmine

#----------------------------------------------------
# Redmineのデプロイ先ディレクトリのオーナー:グループ
#----------------------------------------------------
redmine_dir_owner: apache
redmine_dir_group: apache

#----------------------------------------------------
# Redmineで使用する日本語フォントファイル
#----------------------------------------------------
redmine_font_path: /usr/share/fonts/truetype/takao-gothic/TakaoPGothic.ttf

#----------------------------------------------------
# pg_hba.confのパス
#----------------------------------------------------
pg_hba_conf_path: /var/lib/pgsql/data/pg_hba.conf

#----------------------------------------------------
# ダウンロードするRubyのソースコード
#----------------------------------------------------
ruby_install_from_source: true
ruby_download_url: https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.3.tar.gz
ruby_version: 2.5.3

work_dir: /tmp/redmine-install-dir

#----------------------------------------------------
# Apacheの.htaccessを制御するファイル
#----------------------------------------------------
httpd_conf_confd: redmine.conf

#----------------------------------------------------
# アクセスをコントロールするIPアドレス／ドメイン
#----------------------------------------------------
requires:
  example.com: Require host example.com
  127.0.0.1: Require ip 127.0.0.1
