---
- name: Install requirements(1)
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - patch

- name: Install Python(CentOS8)
  ansible.builtin.package:
    name: python3-devel
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: Install psycopg2(CentOS8)
  ansible.builtin.pip:
    name: psycopg2
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: Delete working directory
  ansible.builtin.file:
    path: '{{ work_dir }}'
    state: absent

- name: Create working directory
  ansible.builtin.file:
    path: '{{ work_dir }}'
    state: directory
    mode: 0755

- name: Create a new PostgreSQL database cluster(CentOS7)
  ansible.builtin.command:
    postgresql-setup initdb
  changed_when: False
  ignore_errors: True
  environment:
    PATH: "{{ ansible_env.PATH }} "
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: Create a new PostgreSQL database cluster(CentOS8)
  ansible.builtin.shell:
    PGSETUP_INITDB_OPTIONS="--encoding=UTF-8 --no-locale" postgresql-setup --initdb
  changed_when: False
  ignore_errors: True
  environment:
    PATH: "{{ ansible_env.PATH }} "
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "8"

- name: Creare patch for adding host-based authentication into pg_hba.conf
  ansible.builtin.template:
    src: pg_hba_conf.patch
    dest: "{{ work_dir }}/pg_hba_conf.patch"
    mode: 0755

- name: Add host-based authentication settings into pg_hba.conf
  ansible.posix.patch:
    src: "{{ work_dir }}/pg_hba_conf.patch"
    dest: '{{ pg_hba_conf_path }}'
    remote_src: yes

- name: Restart postgresql.service
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes

- name: Add privilege escalation to user 'postgres'
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/postgres
    owner: root
    group: root
    mode: 0440
    line: "%{{ ansible_user_id }} ALL=(postgres) NOPASSWD: ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"
  environment:
    PATH:
      "{{ ansible_env.PATH }} "

- name: Create PostgreSQL user
  become: True
  become_user: postgres
  become_method: sudo
  community.general.postgresql_user:
    name: redmine
    password: '{{ db_password }}'

- name: Create database
  become: True
  become_user: postgres
  become_method: sudo
  community.general.postgresql_db:
    name: redmine
    encoding: UTF-8
    lc_collate: ja_JP.UTF-8
    lc_ctype: ja_JP.UTF-8
    template: template0

- name: Remove privilege escalation from user 'postgres'
  ansible.builtin.file:
    path: /etc/sudoers.d/postgres
    state: absent
